// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: scalar.proto

package scalar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalarMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Double float64 `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	Float  float32 `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	Int32  int32   `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64  int64   `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
}

func (x *ScalarMessage) Reset() {
	*x = ScalarMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scalar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScalarMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarMessage) ProtoMessage() {}

func (x *ScalarMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarMessage.ProtoReflect.Descriptor instead.
func (*ScalarMessage) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarMessage) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *ScalarMessage) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *ScalarMessage) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *ScalarMessage) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

var File_scalar_proto protoreflect.FileDescriptor

var file_scalar_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x74, 0x65, 0x73, 0x74, 0x22, 0x69, 0x0a, 0x0d, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x66, 0x6c,
	0x6f, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x42,
	0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scalar_proto_rawDescOnce sync.Once
	file_scalar_proto_rawDescData = file_scalar_proto_rawDesc
)

func file_scalar_proto_rawDescGZIP() []byte {
	file_scalar_proto_rawDescOnce.Do(func() {
		file_scalar_proto_rawDescData = protoimpl.X.CompressGZIP(file_scalar_proto_rawDescData)
	})
	return file_scalar_proto_rawDescData
}

var file_scalar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scalar_proto_goTypes = []interface{}{
	(*ScalarMessage)(nil), // 0: test.ScalarMessage
}
var file_scalar_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scalar_proto_init() }
func file_scalar_proto_init() {
	if File_scalar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scalar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScalarMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scalar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scalar_proto_goTypes,
		DependencyIndexes: file_scalar_proto_depIdxs,
		MessageInfos:      file_scalar_proto_msgTypes,
	}.Build()
	File_scalar_proto = out.File
	file_scalar_proto_rawDesc = nil
	file_scalar_proto_goTypes = nil
	file_scalar_proto_depIdxs = nil
}
