// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: repeated.proto

package repeated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Foo) Reset() {
	*x = Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repeated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_repeated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_repeated_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Bar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo *Foo `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
}

func (x *Bar) Reset() {
	*x = Bar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repeated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_repeated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_repeated_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

type RepeatedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tests []string `protobuf:"bytes,1,rep,name=tests,proto3" json:"tests,omitempty"`
	Foos  []*Foo   `protobuf:"bytes,2,rep,name=foos,proto3" json:"foos,omitempty"`
	Bars  []*Bar   `protobuf:"bytes,3,rep,name=bars,proto3" json:"bars,omitempty"`
}

func (x *RepeatedMessage) Reset() {
	*x = RepeatedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repeated_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedMessage) ProtoMessage() {}

func (x *RepeatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_repeated_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedMessage.ProtoReflect.Descriptor instead.
func (*RepeatedMessage) Descriptor() ([]byte, []int) {
	return file_repeated_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedMessage) GetTests() []string {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *RepeatedMessage) GetFoos() []*Foo {
	if x != nil {
		return x.Foos
	}
	return nil
}

func (x *RepeatedMessage) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

var File_repeated_proto protoreflect.FileDescriptor

var file_repeated_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x74, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x22, 0x0a, 0x03, 0x42, 0x61, 0x72, 0x12, 0x1b, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x6f, 0x6f,
	0x52, 0x03, 0x66, 0x6f, 0x6f, 0x22, 0x65, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1d,
	0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x46, 0x6f, 0x6f, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x73, 0x12, 0x1d, 0x0a,
	0x04, 0x62, 0x61, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x42, 0x61, 0x72, 0x52, 0x04, 0x62, 0x61, 0x72, 0x73, 0x42, 0x10, 0x5a, 0x0e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_repeated_proto_rawDescOnce sync.Once
	file_repeated_proto_rawDescData = file_repeated_proto_rawDesc
)

func file_repeated_proto_rawDescGZIP() []byte {
	file_repeated_proto_rawDescOnce.Do(func() {
		file_repeated_proto_rawDescData = protoimpl.X.CompressGZIP(file_repeated_proto_rawDescData)
	})
	return file_repeated_proto_rawDescData
}

var file_repeated_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_repeated_proto_goTypes = []interface{}{
	(*Foo)(nil),             // 0: test.Foo
	(*Bar)(nil),             // 1: test.Bar
	(*RepeatedMessage)(nil), // 2: test.RepeatedMessage
}
var file_repeated_proto_depIdxs = []int32{
	0, // 0: test.Bar.foo:type_name -> test.Foo
	0, // 1: test.RepeatedMessage.foos:type_name -> test.Foo
	1, // 2: test.RepeatedMessage.bars:type_name -> test.Bar
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_repeated_proto_init() }
func file_repeated_proto_init() {
	if File_repeated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_repeated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repeated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repeated_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_repeated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repeated_proto_goTypes,
		DependencyIndexes: file_repeated_proto_depIdxs,
		MessageInfos:      file_repeated_proto_msgTypes,
	}.Build()
	File_repeated_proto = out.File
	file_repeated_proto_rawDesc = nil
	file_repeated_proto_goTypes = nil
	file_repeated_proto_depIdxs = nil
}
